from .address_book import AddressBook
from .birthday import Birthday
from .email import Email
from .field import Field
from .name import Name
from .note import Note
from .notes_book import NotesBook
from .phone import Phone
from .record import Record
from .tag import Tag
